name: SopPrefix
main: net.enelson.sopprefix.SopPrefixPlugin
version: 0.0.1-SNAPSHOT
api-version: 1.16
depend: [LuckPerms, SopLib]
softdepend: [PlaceholderAPI]

commands:
  prefix:
    usage: /prefix
    aliases: [sopprefix]
    permission: sopprefix.use
  suffix:
    usage: /suffix
    permission: sopprefix.use

permissions:
  sopprefix.use:
    default: true
  sopprefix.admin:
    default: op
